get:
  tags:
    - Tasks
  summary: Get all task assignees
  description: Get information as a list of all task assignees.
  operationId: getTaskAssignees
  parameters:
    - $ref: '../../parameters/_index.yaml#/Accept-Language'
    - $ref: '../../parameters/_index.yaml#/count'
    - $ref: '../../parameters/_index.yaml#/offset'
    - $ref: '../../parameters/_index.yaml#/sort_field'
    - $ref: '../../parameters/_index.yaml#/sort_direction'
    - $ref: '../../parameters/_index.yaml#/task_id_path'
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  task_assignees:
                    type: array
                    description: List of all task assignees.
                    items:
                      $ref: '../../schemas/_index.yaml#/TaskAssignee'
                  total_items:
                    type: integer
                    description: The number of all found task assignees.
                    example: 1
    '400':
      $ref: '../../api.yaml#/components/responses/BadRequest'
    '401':
      $ref: '../../api.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../../api.yaml#/components/responses/Forbidden'
    '404':
      $ref: '../../api.yaml#/components/responses/NotFound'
    '405':
      $ref: '../../api.yaml#/components/responses/NotAllowed'
    '429':
      $ref: '../../api.yaml#/components/responses/TooManyRequests'
    '500':
      $ref: '../../api.yaml#/components/responses/InternalServerError'
    '503':
      $ref: '../../api.yaml#/components/responses/ServiceUnavailable'
  x-codeSamples:
    - lang: PHP
      label: CareCloud SDK
      source: |
        use CrmCareCloud\Webservice\RestApi\Client\ApiException;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\CareCloud;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Config;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Data\AuthTypes;

        require_once '../vendor/autoload.php';

        $project_uri = 'https://yourapiurl.com/webservice/rest-api/enterprise-interface/v1.0';
        $login = 'login';
        $password = 'password';
        $external_app_id = 'application_id';
        $auth_type = AuthTypes::BEARER_AUTH;

        $config = new Config($project_uri, $login, $password, $external_app_id, $auth_type);

        $care_cloud = new CareCloud($config);

        // Set Header parameter Accept-Language
        $accept_language = 'en'; //	string | The unique ID of the language code by ISO 639-1 Default: cs, en-gb;q=0.8

        // Set path parameters
        $task_id = '8bed991c68a470e7aaeffbf048'; // string | The unique ID of the task

        // Set query parameters
        $count = 10; // integer >= 1 | The number of records to return (optional, default is 100)
        $offset = 0; // integer | The number of records from a collection to skip (optional, default is 0)
        $sort_field = null; // string | One of the query string parameters for sorting (optional, default is null)
        $sort_direction = 'DESC'; // string | Direction of sorting the response list (optional, default is null)

        // Call endpoint and get data
        try
        {
            $get_assignees = $care_cloud->tasksApi()->getTaskAssignees(
                $task_id,
                $accept_language,
                $count,
                $offset,
                $sort_field,
                $sort_direction
            );
            $assignees = $get_assignees->getData()->getTaskAssignees();
            $total_items = $get_assignees->getData()->getTotalItems();
            var_dump($assignees);
            var_dump($total_items);
        }
        catch(ApiException $e)
        {
            die(var_dump($e->getResponseBody() ?: $e->getMessage()));
        }
post:
  tags:
    - Tasks
  summary: Create a task assignee
  description: >
    Add a new assignee to the task.<br/>
    ⚠️ Endpoint is available only in the Enterprise interface.<br/>
  operationId: postTaskAssignee
  parameters:
    - $ref: '../../parameters/_index.yaml#/Accept-Language'
    - $ref: '../../parameters/_index.yaml#/task_id_path'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            task_assignee:
              $ref: '../../schemas/_index.yaml#/TaskAssignee'
          required:
            - task_assignee
  responses:
    '201':
      description: Created
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  task_assignee_id:
                    type: string
                    description: The unique ID of the task assignee in CareCloud.
                    example: "86e05affc7a7abefcd513ab400"
    '400':
      $ref: '../../api.yaml#/components/responses/BadRequest'
    '401':
      $ref: '../../api.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../../api.yaml#/components/responses/Forbidden'
    '404':
      $ref: '../../api.yaml#/components/responses/NotFound'
    '405':
      $ref: '../../api.yaml#/components/responses/NotAllowed'
    '429':
      $ref: '../../api.yaml#/components/responses/TooManyRequests'
    '500':
      $ref: '../../api.yaml#/components/responses/InternalServerError'
    '503':
      $ref: '../../api.yaml#/components/responses/ServiceUnavailable'
  x-codeSamples:
    - lang: PHP
      label: CareCloud SDK
      source: |
        use CrmCareCloud\Webservice\RestApi\Client\ApiException;
        use CrmCareCloud\Webservice\RestApi\Client\Model\TaskAssignee;
        use CrmCareCloud\Webservice\RestApi\Client\Model\TaskIdAssigneesBody;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\CareCloud;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Config;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Data\AuthTypes;

        require_once '../vendor/autoload.php';

        $project_uri = 'https://yourapiurl.com/webservice/rest-api/enterprise-interface/v1.0';
        $login = 'login';
        $password = 'password';
        $external_app_id = 'application_id';
        $auth_type = AuthTypes::BEARER_AUTH;

        $config = new Config($project_uri, $login, $password, $external_app_id, $auth_type);

        $care_cloud = new CareCloud($config);

        // Set Header parameter Accept-Language
        $accept_language = 'en'; //	string | The unique ID of the language code by ISO 639-1 Default: cs, en-gb;q=0.8

        // Set path parameters
        $task_id = '8bed991c68a470e7aaeffbf048'; // string | The unique ID of the task

        // Set the task assignee info
        $task_assignee = new TaskAssignee();
        $task_assignee->setUserId('8a84da45ed2c825a741a321d50'); // string | The unique ID of the assigned user

        // Set the request body
        $body = new TaskIdAssigneesBody();
        $body->setTaskAssignee($task_assignee);

        // Call endpoint and post data
        try
        {
            $post_assignee = $care_cloud->tasksApi()->postTaskAssignee($body, $task_id, $accept_language);
            $task_assignee_id = $post_assignee->getData()->getTaskAssigneeId();
            var_dump($task_assignee_id);
        }
        catch(ApiException $e)
        {
            die(var_dump($e->getResponseBody() ?: $e->getMessage()));
        }