post:
  tags:
    - Product brands
  summary: Create a batch of product brands
  description: >
    Batch process helps to add multiple product brands in one request.<br/>
    ⚠️ Endpoint is available only in the Enterprise interface.<br/>
  operationId: postBulkProductBrands
  parameters:
    - $ref: '../../parameters/_index.yaml#/Accept-Language'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            product_brands:
              type: array
              description: List of the CareCloud product brands.
              items:
                $ref: '../../schemas/_index.yaml#/ProductBrand'
            error_processing:
              type: integer
              enum:
                - 1
                - 2
              description: "The parameter describes the batch method behavior in case of error occurs. *Possible values are: 1 - It returns the first error found and rollback all previous changes (this is also the default behavior if the parameter is not set) / 2 - It creates all valid records and creates an error report from failed attempts.*"
          required:
            - product_brands
  responses:
    '204':
      description: No Content
    '400':
      $ref: '../../api.yaml#/components/responses/BadRequest'
    '401':
      $ref: '../../api.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../../api.yaml#/components/responses/Forbidden'
    '404':
      $ref: '../../api.yaml#/components/responses/NotFound'
    '405':
      $ref: '../../api.yaml#/components/responses/NotAllowed'
    '429':
      $ref: '../../api.yaml#/components/responses/TooManyRequests'
    '500':
      $ref: '../../api.yaml#/components/responses/InternalServerError'
    '503':
      $ref: '../../api.yaml#/components/responses/ServiceUnavailable'
  x-codeSamples:
    - lang: PHP
      label: CareCloud SDK
      source: |
        use CrmCareCloud\Webservice\RestApi\Client\ApiException;
        use CrmCareCloud\Webservice\RestApi\Client\Model\ProductBrand;
        use CrmCareCloud\Webservice\RestApi\Client\Model\ProductbrandsBatchBody;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\CareCloud;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Config;
        use CrmCareCloud\Webservice\RestApi\Client\SDK\Data\AuthTypes;

        require_once '../vendor/autoload.php';

        $project_uri = 'https://yourapiurl.com/webservice/rest-api/enterprise-interface/v1.0';
        $login = 'login';
        $password = 'password';
        $external_app_id = 'application_id';
        $auth_type = AuthTypes::BEARER_AUTH;

        $config = new Config($project_uri, $login, $password, $external_app_id, $auth_type);

        $care_cloud = new CareCloud($config);

        // Set Header parameter Accept-Language
        $accept_language = 'en'; //	string | The unique ID of the language code by ISO 639-1 Default: cs, en-gb;q=0.8

        // Set product brand info
        $product_brand = new ProductBrand();
        $product_brand->setName('Test brand'); // string | The name of the product brand
        $product_brand->setExternalId('123'); // string | The unique external ID of the product brand

        // Set the request body
        $body = new ProductbrandsBatchBody();
        $body->setProductBrands(array($product_brand));

        // Call endpoint and post data
        try
        {
            $care_cloud->productBrandsApi()->postBulkProductBrands($body, $accept_language);
        }
        catch(ApiException $e)
        {
            die(var_dump($e->getResponseBody() ?: $e->getMessage()));
        }
