post:
  tags:
    - Product reservations
  summary: Set one or multiple external reservation codes of different types to the product reservation
  description: >
    Set one or multiple external reservation codes of different types to the product reservation.<br/>
    The method will set all the reservation codes from the request.<br/>
    If a reservation code type already exists in the reservation, it will be replaced with a new value from the request. If the request does not contain the reservation code type already in the reservation, CareCloud will make no changes to the reservation code.
  operationId: postProductReservationSetExternalReservationCode
  parameters:
    - $ref: '../../parameters/_index.yaml#/Accept-Language'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            product_reservation_id:
              type: string
              description: The unique ID of the product reservation.
              example: "81eaeea13b8984a169c490a325"
            external_reservation_codes:
              type: array
              items:
                $ref: '../../schemas/_index.yaml#/ExternalCode'
              description: List of the external reservation codes. Id codes can have different sources. Please get in touch with your account manager for the list of ID sources.
          required:
            - product_reservation_id
            - external_reservation_codes
  responses:
    '204':
      description: No Content
    '400':
      $ref: '../../api.yaml#/components/responses/BadRequest'
    '401':
      $ref: '../../api.yaml#/components/responses/Unauthorized'
    '403':
      $ref: '../../api.yaml#/components/responses/Forbidden'
    '404':
      $ref: '../../api.yaml#/components/responses/NotFound'
    '405':
      $ref: '../../api.yaml#/components/responses/NotAllowed'
    '429':
      $ref: '../../api.yaml#/components/responses/TooManyRequests'
    '500':
      $ref: '../../api.yaml#/components/responses/InternalServerError'
    '503':
      $ref: '../../api.yaml#/components/responses/ServiceUnavailable'