type: object
description: Product reservation external list type structure
properties:
  product_reservation_external_list_type_id:
    type: string
    readOnly: true
    description: The unique id of the external list type
    example: 8bed991c68a470e7aaeffbf048
  name:
    type: string
    readOnly: true
    description: Name of the external list type
    example: 'Webshop reservations'