type: object
description: Product resource for the batch processing
properties:
  product_id:
    type: string
    readOnly: true
    description: The unique id of the product
    example: '89bdacbffb5c82f2c52cb9ae8f'
  name:
    type: string
    readOnly: false
    description: Name of the product
    example: "Vodka tonic"
  code:
    type: string
    readOnly: false
    description: Code of the product
    example: '649'
  plu_ids:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/PluId'
    readOnly: false
    description: An array of all available pluIds from the particular product lists (default is Product ID from Global product list (consist cleaned data - unique id for every product across all POS systems))
  product_group_id:
    type: string
    readOnly: false
    description: The unique id for the product group
    example: '85cfc89601efa1ba2c2aa3b6a0'
  product_brand_id:
    type: string
    readOnly: false
    description: The unique id for the product brand
    example:
required:
  - name
  - code
  - plu_ids