type: object
description: Product group resource
properties:
  product_group_id:
    type: string
    readOnly: true
    description: The unique id of the product group
    example: '83d1d11ea3884a5d33253fe214'
  name:
    type: string
    readOnly: false
    description: Name of the product group
    example: "The best brand"
  parent_product_group_id:
    type: string
    readOnly: false
    description: The unique id of the parent product group. If `parent_external_id` is also set, both parameters have to represent the same product group.
    example: '1884a5d11ea3884a5d332534a5f'
  parent_external_id:
    type: string
    readOnly: false
    description: The unique external id of the parent product group. If `parent_product_group_id` is also set, both parameters have to represent the same product group.
    example: '678'
  code:
    type: string
    readOnly: false
    description: Code of the product group
    example: '567829'
  external_id:
    type: string
    readOnly: false
    description: The external unique id of the product group
    example: '953'
  store_id:
    type: string
    readOnly: false
    description: The unique id of the store where the product group is valid. The product group is global if this value is not set
    example: '83d1d11ea3884a5d33253fe214'
  last_change:
    type: string
    readOnly: true
    description: Date and time of the last change *(YYYY-MM-DD HH:MM:SS)*
    example: "2019-02-08 15:35:09"
  state:
    type: integer
    enum:
      - 0
      - 1
      - 2
    readOnly: true
    description: |
      State of the product group
      *Possible values are: 0 - deleted / 1 - active / 2 - non active*
    example: 1
required:
  - name
  - external_id