type: object
description: Product reservation progress history structure.
properties:
  reservation_progress_id:
    type: integer
    readOnly: true
    description: ID of the product reservation progress.
    example: 4
  reservation_progress_text:
    type: string
    readOnly: true
    description: String of the product reservation progress.
    example: "Delivered"
  reservation_progress_time:
    type: string
    readOnly: true
    description: "Timestamp of the product reservation progress change. Format: `YYYY-MM-DD HH:MM:SS`. All times are in the local timezone."
    example: "2012-11-22 20:57:04"