type: object
description: Product resource for the batch processing.
properties:
  product_id:
    type: string
    readOnly: true
    description: The unique ID of the product.
    example: "81c14010c101966aefbb4738fc"
  name:
    type: string
    readOnly: false
    description: Name of the product.
    example: "Custom product N12"
  code:
    type: string
    readOnly: false
    description: Code of the product.
    example: "64912"
  plu_ids:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/PluId'
    readOnly: false
    description: An array of all available pluIDs from the particular product lists (default is Product ID from Global product list (consist cleaned data - unique ID of every product across all POS systems)).
  product_group_id:
    type: string
    readOnly: false
    description: The unique ID of the product group. If `product_group_external_id` is also set, both parameters have to represent the same product group.
    example: "83d1d11ea3884a5d33253fe214"
  product_group_external_id:
    type: string
    readOnly: false
    description: The unique external ID of the product group. If `product_group_id` is also set, both parameters have to represent the same product group.
    example: "23"
  product_brand_id:
    type: string
    readOnly: false
    description: The unique ID of the product brand. If `product_brand_external_id` is also set, both parameters have to represent the same product brand.
    example: "82db62087b0f79a6e14e5747e7"
  product_brand_external_id:
    type: string
    readOnly: false
    description: The unique external ID of the product brand. If `product_brand_id` is also set, both parameters have to represent the same product brand.
    example: "71"
  store_id:
    type: string
    readOnly: false
    description: The unique ID of the store where the product group is valid. The product group is global if this value is not set.
    example: "83d1d11ea3884a5d33253fe214"
  property_records:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/PropertyRecord'
    readOnly: false
    description: List of an additional properties.
  prices:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/Price'
required:
  - name
  - plu_ids