type: object
description: |
  Product reservation resource.

  <p class="warning">⚠️Structure has to contain reservation codes or product reservation items</p>
properties:
  product_reservation_id:
    type: string
    readOnly: true
    description: The unique ID of the product reservation.
    example: '81eaeea13b8984a169c490a325'
  customer_id:
    type: string
    readOnly: false
    description:   The unique ID of the customer, owner of the product reservation.
    example: '8ea2591121e636086a4a9c0992'
  store_id:
    type: string
    readOnly: false
    description: The unique ID of the store tied to the reservation.
    example: '82db62087b0f79a6e14e5747e7'
  reservation_codes:
    type: array
    items:
      type: string
    readOnly: true
    description: Reservation codes of the reservation from CareCloud.
    example: [3]
  external_reservation_codes:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/ExternalCode'
    readOnly: false
    description: List of the external reservation codes. Id codes can have different sources. Please get in touch with your account manager for the list of ID sources.
  benefit_codes:
    type: array
    items:
      type: string
    readOnly: false
    description: List of the benefit (rewards, vouchers) codes used in a reservation. After the reservation is delivered, all benefits are applied on the customer account.
    example: [ "PTV116", "PTV120" ]
  product_reservation_source_id:
    type: string
    readOnly: false
    description: The unique ID of the product reservation source.
    example: "8bed991c68a470e7aaeffbf048"
  pickup_date:
    type: string
    readOnly: true
    description: Date of the reservation pickup in the tied store. *(YYYY-MM-DD)*
    example: '2020-04-20'
  customers_note:
    type: string
    readOnly: false
    description: Customer’s note for the merchant.
    example: "Please add a gift package"
  total_price:
    type: number
    format: float
    readOnly: false
    description: Total price of reservation. If currency_id is set, then total_price is mandatory.
    example: 69
  currency_id:
    type: string
    readOnly: false
    description: ID of the currency. If total_price is set, then currency_id is mandatory.
    example: "8bed991c68a470e7aaeffbf048"
  product_reservation_items:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/ProductReservationItem'
    readOnly: false
    description: List of the Product Reservation Items.
  external_purchase_id:
    type: string
    readOnly: false
    description: The unique external ID of the purchase.
    example: "20231412"
  utm:
    type: object
    $ref: '../schemas/_index.yaml#/UTM'
    readOnly: false
    description: UTM structure for data from email campaign.
  actual_state:
    type: integer
    enum:
      - 0
      - 1
      - 2
      - 2
      - 4
      - 5
      - 6
      - 7
      - 8
    readOnly: true
    description: |
      Current progress of the product reservation.
      *Possible values: 0 - Canceled / 1 - Entered / 2 - Accepted / 3 - Ready / 4 - Delivered / 5 - In progress / 6 - Not Picked up / 7 - Ordered / 8 - Being solved /*
    example: 5
  reservation_progress_history:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/ProductReservationProgress'
    readOnly: true
    description: History of the product reservation progress. Product reservation progress is sorted in descending order by time.
  comments:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/ProductReservationComment'
    readOnly: true
    description: Product reservation comments. Comments are sorted in descending order by time.
  last_change:
    type: string
    readOnly: true
    description: Date and time of the last change. *(YYYY-MM-DD HH:MM:SS)*
    example: "2020-04-20 11:23:35"
  state:
    type: integer
    enum:
      - 0
      - 1
      - 2
    readOnly: true
    description: |
      State of the product reservation.
      *Possible values are: 0 - deleted / 1 - active *
    example: 1
required:
  - customer_id
  - store_id
  - product_reservation_source_id