type: object
description: Product resource
properties:
  product_id:
    type: string
    readOnly: true
    description: The unique id of the product
    example: '85d6598db0bf3f62afd5db8507'
  name:
    type: string
    readOnly: false
    description: Name of the product
    example: "Google phone 1"
  code:
    type: string
    readOnly: false
    description: Code of the product
    example: '649'
  external_id:
    type: string
    readOnly: false
    description: The external unique id of the product. This parameter is depracated. Please use parameter `plu_ids`
    example: 'NKBD7TB'
    deprecated: true
  plu_ids:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/PluId'
    readOnly: false
    description: An array of all available pluIds from the particular product lists (default is Product ID from Global product list (consist cleaned data - unique id of every product across all POS systems)).
  product_group_id:
    type: string
    readOnly: false
    description: The unique id of the product group
    example: '82de12eb8b138791e678fd11c3'
  product_brand_id:
    type: string
    readOnly: false
    description: The unique id of the product brand
    example: "82db62087b0f79a6e14e5747e7"
  additional_properties:
    type: array
    items:
      $ref: '../schemas/_index.yaml#/PropertyRecord'
    readOnly: false
    description: List of additional properties
  last_change:
    type: string
    readOnly: true
    description: Date and time of the last change *(YYYY-MM-DD HH:MM:SS)*
    example: "2022-11-01 13:15:24"
  state:
    type: integer
    enum:
      - 0
      - 1
      - 2
    readOnly: true
    description: |
      State of the product
      *Possible values are: 0 - deleted / 1 - active / 2 - non active*
    example: 1